#!/bin/sh

. /Applications/prestashop-1.7.0.4-1/scripts/setenv.sh

exec /Applications/prestashop-1.7.0.4-1/php/sbin/.php-fpm.bin -y /Applications/prestashop-1.7.0.4-1/php/etc/php-fpm.conf -p /Applications/prestashop-1.7.0.4-1/php/var/ -c /Applications/prestashop-1.7.0.4-1/php/etc/php.ini "$@"
